#! /bin/bash

set -euo pipefail

cd $(dirname ${BASH_SOURCE[0]})/..

UNAME_S=$(uname -s)

case ${UNAME_S} in
	Linux*)
		if sudo -v; then
			sudo apt-get update
			sudo apt-get install \
				-y \
				cmake \
				ninja-build
		fi
		;;
	Darwin*)
		brew install \
			cmake \
			llvm \
			ninja
		BIN_DIR=${HOME}/.local/bin
		mkdir -p ${BIN_DIR}
		ln -s "$(brew --prefix llvm)/bin/clang-format" ${BIN_DIR}/clang-format
		ln -s "$(brew --prefix llvm)/bin/clang-tidy" ${BIN_DIR}/clang-tidy
		;;
	*)
		echo "Unsupported platform: ${UNAME_S}"
		exit 1
		;;
esac
